# action.yml
name: "PyHC Environment Compatibility Checker"
description: "Check package compatibility with PyHC Environment dependencies"
author: PyHC Community

branding:
  icon: "layers"
  color: "green"

inputs:
  project-file:
    description: "Path to pyproject.toml file"
    required: false
    default: "pyproject.toml"
  pyhc-packages-url:
    description: "URL to PyHC Environment packages.txt"
    required: false
    default: "https://raw.githubusercontent.com/heliophysicsPy/pyhc-docker-environment/main-v2/docker/pyhc-environment/contents/packages.txt"
  pyhc-constraints-url:
    description: "URL to PyHC Environment constraints.txt"
    required: false
    default: "https://raw.githubusercontent.com/heliophysicsPy/pyhc-docker-environment/main-v2/docker/pyhc-environment/contents/constraints.txt"
  extras:
    description: "Extras selection: auto | none | comma-separated list (e.g., mth5,vires)"
    required: false
    default: "auto"

outputs:
  compatible:
    description: "Whether the package is compatible with PyHC Environment"
    value: ${{ steps.check.outputs.compatible }}
  conflicts:
    description: "Number of conflicts found"
    value: ${{ steps.check.outputs.conflicts }}

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install uv
      shell: bash
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Verify uv installation
      shell: bash
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        uv --version

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install packaging tomlkit requests pyyaml

    - name: Run PyHC compatibility check
      id: check
      shell: bash
      env:
        PYTHONPATH: ${{ github.action_path }}/../src
      run: |
        export PATH="$HOME/.local/bin:$PATH"

        # Ensure git history/tags are available for setuptools_scm versioning
        if [ -d .git ]; then
          if git rev-parse --is-shallow-repository >/dev/null 2>&1; then
            git fetch --quiet --unshallow --tags --force --prune
          else
            git fetch --quiet --tags --force --prune
          fi
        fi

        PACKAGES_ARG=""
        if [ -n "${{ inputs.pyhc-packages-url }}" ]; then
          PACKAGES_ARG="--packages ${{ inputs.pyhc-packages-url }}"
        fi

        CONSTRAINTS_ARG=""
        if [ -n "${{ inputs.pyhc-constraints-url }}" ]; then
          CONSTRAINTS_ARG="--constraints ${{ inputs.pyhc-constraints-url }}"
        fi

        EXTRAS_ARG=""
        if [ -n "${{ inputs.extras }}" ]; then
          EXTRAS_ARG="--extras ${{ inputs.extras }}"
        fi

        python -m pyhc_actions.env_compat.main $PACKAGES_ARG $CONSTRAINTS_ARG $EXTRAS_ARG "${{ inputs.project-file }}"
        EXIT_CODE=$?

        if [ $EXIT_CODE -eq 0 ]; then
          echo "compatible=true" >> "$GITHUB_OUTPUT"
          # conflicts output is populated by pyhc_actions.env_compat.main
        else
          echo "compatible=false" >> "$GITHUB_OUTPUT"
        fi

        exit $EXIT_CODE
